export const mock_donation_list = [
  {
    id: 35196,
    order: 7,
    parent_project_id: 0,
    title: 'Bantu Korban Kebakaran Palembang',
    expired: 2147483647,
    image: 'https://kitabisa-userupload-01.s3-ap-southeast-1.amazonaws.com/_production/campaign/35196/31__1497021712_77171538167_f.jpg',
    days_remaining: 4,
    donation_received: 60826,
    campaigner: 'Reza Saputra',
    campaigner_type: 'PERSONAL',
    campaigner_badge: '',
    campaigner_is_verified: false,
    category_name: 'Bencana Alam',
    is_forever_running: true,
    is_open_goal: false,
    request_userdata: false,
    donation_target: 1000000000,
    donation_percentage: 0.000060826,
    short_url: 'kebakaranpalembang',
    is_featured: 0,
    custom_fb_pixel: '',
  },
  {
    id: 94597,
    order: 1,
    parent_project_id: 0,
    title: '#BisaBangkit Bersama Kitabisa',
    expired: 2147483647,
    image: 'https://img.staging.kitabisa.cc/size/664x357/0f9a7205-79ef-49c9-a95a-49347fbd00a6.jpg',
    days_remaining: 0,
    donation_received: 178613497,
    campaigner: 'Kitabisa.com',
    campaigner_type: 'PERSONAL',
    campaigner_badge: 'https://assets.kitabisa.com/images/icon__verified-user.svg',
    campaigner_is_verified: true,
    category_name: 'Bencana Alam',
    is_forever_running: true,
    is_open_goal: false,
    request_userdata: false,
    donation_target: 500000000,
    donation_percentage: 0.357227,
    short_url: 'bisabangkit',
    is_featured: 0,
    custom_fb_pixel: '',
  },
  {
    id: 42043,
    order: 6,
    parent_project_id: 0,
    title: 'Bantu sekolah dan rumah diterjang banjir',
    expired: 2147483647,
    image: 'https://kitabisa-userupload-01.s3-ap-southeast-1.amazonaws.com/_production/campaign/42043/31_42043_1507197617_794756_f.png',
    days_remaining: 3,
    donation_received: 856491,
    campaigner: 'Ipmkabbogor',
    campaigner_type: 'PERSONAL',
    campaigner_badge: '',
    campaigner_is_verified: false,
    category_name: 'Bencana Alam',
    is_forever_running: true,
    is_open_goal: false,
    request_userdata: false,
    donation_target: 300000000,
    donation_percentage: 0.00285497,
    short_url: 'banjirbogor',
    is_featured: 0,
    custom_fb_pixel: '',
  },
];
